baseURL = "https://kramkarthik.com/"
languageCode = "en-us"
title = "Ramkarthik Krishnamurthy"
theme = "basics"
# disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "Ramkarthik Krishnamurthy"
    description = "Personal blog of Ramkarthik Krishnamurthy."
    keywords = "ramkarthik, krishnamurthy"
    github = "Ramkarthik"
    twitter = "Ramkarthik"
    email = "ramkarthikkrishnamurthy@gmail.com"